- name: Setting up apache webservers on amazon linux servers  #Play1 configure apache on amazon linux 2 hosts
  hosts: amazon-nodes

  tasks:
    - name: Upgrade all packages on the server #yum update -y
      ansible.builtin.yum:
        name: '*'
        state: latest
    
    - name: Install the latest version of Apache #yum install httpd -y
      ansible.builtin.yum:
        name: httpd
        state: latest
        
    - name: Start service httpd, if not started # systemctl start http
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Enable service httpd at server launch # systemctl enable httpd
      ansible.builtin.service:
        name: httpd
        enabled: yes

    - name: Copy index.html file from the controller to the nodes at /var/www/html
      ansible.builtin.copy:
        src: /root/index.html
        dest: /var/www/html/


- name: Setting up apache webservers on ubuntu servers   # Play2 configure apache on ubuntu hosts
  hosts: ubuntu-nodes
  
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Install apache httpd  
      ansible.builtin.apt:
        name: apache2
        state: latest

    - name: Start service httpd, if not started # systemctl start http
      ansible.builtin.service:
        name: apache2
        state: started

    - name: Enable service httpd at server launch # systemctl enable httpd
      ansible.builtin.service:
        name: apache2
        enabled: yes

    - name: Copy index.html file from the controller to the nodes at /var/www/html
      ansible.builtin.copy:
        src: /root/webs/index.html
        dest: /var/www/html/

    - name: Install the latest git # yum install git -y
          ansible.builtin.yum:
            name: git
            state: latest



- name: ping all the servers
  hosts: all
  
  tasks:
    - name: ping all the nodes
      ansible.builtin.ping: